### ISSUE TITLE
perfsee github app will auto create compare in my closed issue

### ISSUE THREAD

**Issue by moonrailgun** [perfsee/perfsee#168]
`perfsee` app will auto create compare in my closed issue after i upload my first bundle info.

I dont think it is a right behaviour.

First, it is a issue, not pr.

Second, it has been closed.

It is a bug or feature?

Some reference:
- https://github.com/msgbyte/tailchat/issues/16
- https://github.com/msgbyte/tailchat/issues/5

**Comment by EYHN** [comment]
This is indeed a bug, the reason is that this commit is associated to a pull request (https://github.com/nonomal/tailchat/pull/16) that does not belong to this repository, and our bot didn't expect this, and comments to the wrong issues (since github pull request and issues share the same number)

We will fix this issue as soon as possible.

**Comment by moonrailgun** [comment]
So in origin design, bot should do nothing? 

But another issue is, why app will found others folk? others not install perfsee app(maybe).

**Comment by EYHN** [comment]
Yes. In this case, bot should do nothing.

We use the github check runs api to find pull requests, and it seems that it can find not only pr from fork to the sourece repo, but also pr from the source repo to fork. Since fork is public, this not have permission issues.

But perfsee will limit the features to the repository where perfsee is installed and will not do anything to other repositories

**Comment by moonrailgun** [comment]
I get it, thanks for your reply. 💯 

But my suggest is listen on webhook event. its means start work after app installed, check passed pr is not meaningful.
